### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/libpcl/lib/libpcl.1.dylib

### ISSUE THREAD

**Issue by vigo** [f/equiv#5]
```
$ equiv 
dyld: Library not loaded: /usr/local/opt/libpcl/lib/libpcl.1.dylib
Referenced from: /usr/local/bin/equiv
Reason: image not found
Trace/BPT trap: 5
```

doesn't work :(

**Comment by hdogan** [comment]
It works after installing libpcl and bdw-gc packages. `brew install libpcl` and `brew install bdw-gc` fixes this temporarily.

**Comment by f** [comment]
I plan to rewrite this using Python since Crystal is a bit "new" :/

**Comment by hdogan** [comment]
These two packages may be added as formula dependencies.

**Comment by f** [comment]
@hdogan It's a good idea, just added them! :) :+1:
